name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-api:latest src/

      - name: Authenticate with GCR and GKE
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-api:latest

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials flask-cluster --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl apply -f k8s/
